# Generated by Django 3.2.6 on 2021-10-31 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField()),
                ('date_employed', models.DateField()),
                ('position', models.CharField(blank=True, max_length=30, null=True)),
                ('area', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('local', models.CharField(blank=True, max_length=100, null=True)),
                ('SSF_no', models.CharField(blank=True, max_length=20, null=True)),
                ('salary', models.IntegerField(blank=True, null=True)),
                ('telephone', models.CharField(blank=True, max_length=13, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransferHistory',
            fields=[
                ('transfers_id', models.IntegerField(auto_created=True, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date_transferred', models.DateField()),
                ('transferred_from', models.CharField(blank=True, max_length=100, null=True)),
                ('from_area', models.CharField(blank=True, max_length=100, null=True)),
                ('transferred_to', models.CharField(blank=True, max_length=100, null=True)),
                ('to_area', models.CharField(blank=True, max_length=100, null=True)),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transfers.staff')),
            ],
        ),
    ]
